### ISSUE TITLE
Going through history of games feedback

### ISSUE THREAD

**Issue by StevenCopeland** [js13kGames/js13kgames.com#2]
I would suggest updating the website so if you click on a different year(lets say 2012) and then you try to get back, it shows every year so instead of just listing 2013, 2014, and 2015, you also list 2016, and 2017. Then it will be easier for other people/me to navigate the website.

**Comment by end3r** [comment]
You're absolutely right - thanks for pointing that out, fixed.

**Comment by StevenCopeland** [comment]
Awesome! Looks great now.
